[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркировка для UI автотестов.
    smoke: Маркировка для смоук автотестов.
    regression: Маркировка для регрессионных автотестов.
    critical: Маркировка для критичных автотестов.
    slow: Маркировка для медленных автотестов.
    registration: Маркировка для автотестов, связанных с регистрацией.
    authorization: Маркировка для автотестов, связанных с авторизацией.
    courses: Маркировка для автотестов, связанных с курсом.